sugarcube-2:
  macros:
    combatWidget:
      name: combatWidget
    initStats:
      name: initStats
    initEnemy:
      name: initEnemy
    initItems:
      name: initItems
    initLoot:
      name: initLoot
    debugCharacter:
      name: debugCharacter
    testMacro:
      name: testMacro
    consumeEnemy:
      name: consumeEnemy
    combatReset:
      name: combatReset
    storeItem:
      name: storeItem
    storeWidget:
      name: storeWidget
    invMacro:
      name: invMacro
    restMacro:
      name: restMacro
    trainMacro:
      name: trainMacro
    timeAction:
      name: timeAction
      container: true
    attackAction:
      name: attackAction
    skillsMacro:
      name: skillsMacro
    genderDropdownMacro:
      name: genderDropdownMacro
    startGameRoutine:
      name: startGameRoutine
    enemyMacro:
      name: enemyMacro
    healthBarMacro:
      name: healthBarMacro
    leaveButtonMacro:
      name: leaveButtonMacro
      container: true
    playerFluffMacro:
      name: playerFluffMacro
    capacityBarMacro:
      name: capacityBarMacro
    clockMacro:
      name: clockMacro
    bugMacro:
      name: bugMacro
    attackSkillsMacro:
      name: attackSkillsMacro
    tabMacro:
      name: tabMacro
    movesetMacro:
      name: movesetMacro
    cityMacro:
      name: cityMacro
    consumeMacro:
      name: consumeMacro
