name: Build

on:
  push:
    branches:
      - v0.2.0

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  cirrusci/flutter:v1.7.8-hotfix.4
      options: --user root
    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: build game
        run: |
          sudo /home/cirrus/sdks/flutter/bin/flutter pub get
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          vendor/tweego --format=sugarcube-2 src/twee/ -o dist/index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist